version: 0.0
os: linux
files:
  - source: src/main/webapp/jsp/
    destination: /opt/tomcat/tomcat-10/webapps/boot/jsp/
    overwrite: yes

  - source: src/main/java/com/
    destination: /opt/tomcat/tomcat-10/webapps/boot/WEB-INF/classes/com/
    overwrite: yes
	
  - source: src/main/resources/mappers/
	destination: /opt/tomcat/tomcat-10/webapps/boot/WEB-INF/classes/mappers/
	overwrite: yes



permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: Scripts/deploy/deploy.sh
      timeout: 60
      runas: ubuntu

